# Site settings
title: New Vision Training Consultants
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  We  help develop and maintain standard at Africa's best hotels. Need help training your staff? Want strategic input to take your establishment forward? Get in contact with us! 
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

gems: [jekyll-paginate]
paginate: 3
paginate_path: "blog/page:num"